export const START_CREATE_FORM = "START_CREATE_FORM";
export const SUCCESS_CREATE_FORM = "SUCCESS_CREATE_FORM";
export const ERROR_CREATE_FORM = "ERROR_CREATE_FORM";

export const START_GET_FORM_DETAILS = "START_GET_FORM_DETAILS";
export const SUCCESS_GET_FORM_DETAILS = "SUCCESS_GET_FORM_DETAILS";
export const ERROR_GET_FORM_DETAILS = "ERROR_GET_FORM_DETAILS";

export const START_UPDATE_FORM_DETAILS = "START_UPDATE_FORM_DETAILS";
export const SUCCESS_UPDATE_FORM_DETAILS = "SUCCESS_UPDATE_FORM_DETAILS";
export const ERROR_UPDATE_FORM_DETAILS = "ERROR_UPDATE_FORM_DETAILS";

export const START_GET_USER_FORMS = "START_GET_USER_FORMS";
export const SUCCESS_GET_USER_FORMS = "SUCCESS_GET_USER_FORMS";
export const ERROR_GET_USER_FORMS = "ERROR_GET_USER_FORMS";
