export const START_CREATE_FORM = "START_CREATE_FORM";
export const SUCCESS_CREATE_FORM = "SUCCESS_CREATE_FORM";
export const ERROR_CREATE_FORM = "ERROR_CREATE_FORM";

export const START_GET_FORM_DETAILS = "START_GET_FORM_DETAILS";
export const SUCCESS_GET_FORM_DETAILS = "SUCCESS_GET_FORM_DETAILS";
export const ERROR_GET_FORM_DETAILS = "ERROR_GET_FORM_DETAILS";

export const START_UPDATE_FORM_DETAILS = "START_UPDATE_FORM_DETAILS";
export const SUCCESS_UPDATE_FORM_DETAILS = "SUCCESS_UPDATE_FORM_DETAILS";
export const ERROR_UPDATE_FORM_DETAILS = "ERROR_UPDATE_FORM_DETAILS";

export const START_GET_USER_FORMS = "START_GET_USER_FORMS";
export const SUCCESS_GET_USER_FORMS = "SUCCESS_GET_USER_FORMS";
export const ERROR_GET_USER_FORMS = "ERROR_GET_USER_FORMS";

export const START_SUBMIT_FORM = "START_SUBMIT_FORM";
export const SUCCESS_SUBMIT_FORM = "SUCCESS_SUBMIT_FORM";
export const ERROR_SUBMIT_FORM = "ERROR_SUBMIT_FORM";

export const START_SINGLE_FORM_RESPONSE = "START_SINGLE_FORM_RESPONSE";
export const SUCCESS_SINGLE_FORM_RESPONSE = "SUCCESS_SINGLE_FORM_RESPONSE";
export const ERROR_SINGLE_FORM_RESPONSE = "ERROR_SINGLE_FORM_RESPONSE";

export const START_GET_SINGLE_RESPONSE = "START_GET_SINGLE_RESPONSE";
export const SUCCESS_GET_SINGLE_RESPONSE = "SUCCESS_GET_SINGLE_RESPONSE";
export const ERROR_GET_SINGLE_RESPONSE = "ERROR_GET_SINGLE_RESPONSE";
