export const START_CREATE_FORM = "START_CREATE_FORM";
export const SUCCESS_CREATE_FORM = "SUCCESS_CREATE_FORM";
export const ERROR_CREATE_FORM = "ERROR_CREATE_FORM";

export const START_GET_FORM_DETAILS = "START_GET_FORM_DETAILS";
export const SUCCESS_GET_FORM_DETAILS = "SUCCESS_GET_FORM_DETAILS";
export const ERROR_GET_FORM_DETAILS = "ERROR_GET_FORM_DETAILS";
